- name: install apache and php packages
  tags: apache, apache2, httpd
  apt:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name}} "
    state: latest

- name: start and enable apache service
  tags: apache, httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change log level for apache
  tags: apache2, apache, Ubuntu
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^LogLevel'
    line: LogLevel warn
  notify: restart_apache

- name: copy html file for site
  tags: apache, apache2, httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
