- name: add ssh key for tbf
  authorized_key:
    user: tbf
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILMl8Oi3YUuqORAvvgT5fLJKZntV7BhHoW9823t7cM44 ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
